CREATE COLUMN TABLE  Allstar ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, lgID char (2) NOT NULL);
CREATE COLUMN TABLE  AwardsManagers ( managerID varchar (10) NOT NULL, awardID varchar (25) NOT NULL, yearID smallint  NOT NULL, lgID char (2) NOT NULL, tie char (1) NULL, notes varchar (100) NULL);
CREATE COLUMN TABLE  AwardsPlayers ( playerID varchar (9) NOT NULL, awardID varchar (255) NOT NULL, yearID smallint  NOT NULL, lgID char (2) NOT NULL, tie char (1) NULL, notes varchar (100) NULL);
CREATE COLUMN TABLE  AwardsShareManagers ( awardID varchar (25) NOT NULL, yearID smallint  NOT NULL, lgID char (2) NOT NULL, managerID varchar (10) NOT NULL, pointsWon integer  NULL, pointsMax integer  NULL, votesFirst integer  NULL);
CREATE COLUMN TABLE  AwardsSharePlayers ( awardID varchar (25) NOT NULL, yearID smallint  NOT NULL, lgID char (2) NOT NULL, playerID varchar (9) NOT NULL, pointsWon double  NULL, pointsMax integer  NULL, votesFirst double  NULL);
CREATE COLUMN TABLE  HOFold ( hofID varchar (10) NOT NULL, yearID integer  NOT NULL, votedBy varchar (10) NULL, ballots smallint  NULL, votes smallint  NULL, inducted char (1) NOT NULL, category varchar (20) NULL);
CREATE COLUMN TABLE  ManagersHalf ( managerID varchar (10) NOT NULL, yearID smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, inseason integer  NULL, half smallint  NOT NULL, G smallint  NOT NULL, W smallint  NOT NULL, L smallint  NOT NULL, rank smallint  NOT NULL);
CREATE COLUMN TABLE  Pitching ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, stint smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, W smallint  NULL, L smallint  NULL, G smallint  NULL, GS smallint  NULL, CG smallint  NULL, SHO smallint  NULL, SV smallint  NULL, IPouts integer  NULL, H smallint  NULL, ER smallint  NULL, HR smallint  NULL, BB smallint  NULL, SO smallint  NULL, BAOpp decimal (5,3) NULL, ERA decimal (5,2) NULL, IBB smallint  NULL, WP smallint  NULL, HBP smallint  NULL, BK smallint  NULL, BFP smallint  NULL, GF smallint  NULL, R smallint  NULL, SH smallint  NULL, SF smallint  NULL, GIDP smallint  NULL);
CREATE COLUMN TABLE  PitchingPost ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, round varchar (10) NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, W smallint  NULL, L smallint  NULL, G smallint  NULL, GS smallint  NULL, CG smallint  NULL, SHO smallint  NULL, SV smallint  NULL, IPouts integer  NULL, H smallint  NULL, ER smallint  NULL, HR smallint  NULL, BB smallint  NULL, SO smallint  NULL, BAOpp double  NULL, ERA double  NULL, IBB smallint  NULL, WP smallint  NULL, HBP smallint  NULL, BK smallint  NULL, BFP smallint  NULL, GF smallint  NULL, R smallint  NULL, SH smallint  NULL, SF smallint  NULL, GIDP smallint  NULL);
CREATE COLUMN TABLE  Salaries ( yearID smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, playerID varchar (9) NOT NULL, salary double  NOT NULL);
CREATE COLUMN TABLE  Schools ( schoolID varchar (15) NOT NULL, schoolName varchar (255) NOT NULL, schoolCity varchar (55) NULL, schoolState varchar (55) NULL, schoolNick varchar (55) NULL);
CREATE COLUMN TABLE  SchoolsPlayers ( playerID varchar (9) NOT NULL, schoolID varchar (15) NOT NULL, yearMin integer  NOT NULL, yearMax integer  NOT NULL);
CREATE COLUMN TABLE  SeriesPost ( yearID smallint  NOT NULL, round varchar (5) NOT NULL, teamIDwinner char (3) NOT NULL, lgIDwinner char (2) NOT NULL, teamIDloser char (3) NOT NULL, lgIDloser char (2) NOT NULL, wins smallint  NOT NULL, losses smallint  NOT NULL, ties integer  NULL);

-- HANA DOESN'T like 2B or 3B so Two_B and Three_B are the replacements
CREATE COLUMN TABLE  Teams ( yearID smallint  NOT NULL, lgID char (2) NOT NULL, teamID char (3) NOT NULL, franchID char (3) NOT NULL, divID char (1) NULL, Rank smallint  NOT NULL, G smallint  NULL, Ghome integer  NULL, W smallint  NULL, L smallint  NULL, DivWin char (1) NULL, WCWin char (1) NULL, LgWin char (1) NULL, WSWin char (1) NULL, R smallint  NULL, AB smallint  NULL, H smallint  NULL, TWO_B smallint  NULL, THREE_B smallint  NULL, HR smallint  NULL, BB smallint  NULL, SO smallint  NULL, SB smallint  NULL, CS smallint  NULL, HBP smallint  NULL, SF smallint  NULL, RA smallint  NULL, ER smallint  NULL, ERA decimal (4,2) NULL, CG smallint  NULL, SHO smallint  NULL, SV smallint  NULL, IPouts integer  NULL, HA smallint  NULL, HRA smallint  NULL, BBA smallint  NULL, SOA smallint  NULL, E integer  NULL, DP integer  NULL, FP decimal (5,3) NULL, name varchar (50) NOT NULL, park varchar (255) NULL, attendance integer  NULL, BPF integer  NULL, PPF integer  NULL, teamIDBR char (3) NULL, teamIDlahman45 char (3) NULL, teamIDretro char (3) NULL);

CREATE COLUMN TABLE  TeamsFranchises ( franchID char (3) NOT NULL, franchName varchar (50) NOT NULL, active char (2) NOT NULL, NAassoc char (3) NULL);
CREATE COLUMN TABLE  TeamsHalf ( yearID smallint  NOT NULL, lgID char (2) NOT NULL, teamID char (3) NOT NULL, Half char (1) NOT NULL, divID char (1) NULL, DivWin char (1) NOT NULL, Rank smallint  NOT NULL, G smallint  NULL, W smallint  NULL, L smallint  NULL);
CREATE COLUMN TABLE  xref_stats ( playerID varchar (10) NOT NULL, statsID integer  NOT NULL, bisID integer  NULL);

-- HANA DOESN'T like 2B or 3B so Two_B and Three_B are the replacements
CREATE COLUMN TABLE  Batting ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, stint smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, G smallint  NULL, G_batting smallint  NULL, AB smallint  NULL, R smallint  NULL, H smallint  NULL, TWO_B smallint  NULL, Three_B smallint  NULL, HR smallint  NULL, RBI smallint  NULL, SB smallint  NULL, CS smallint  NULL, BB smallint  NULL, SO smallint  NULL, IBB smallint  NULL, HBP smallint  NULL, SH smallint  NULL, SF smallint  NULL, GIDP smallint  NULL, G_old smallint  NULL);

CREATE COLUMN TABLE  Fielding ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, stint smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, POS char (2) NOT NULL, G smallint  NULL, GS smallint  NULL, InnOuts integer  NULL, PO smallint  NULL, A smallint  NULL, E smallint  NULL, DP smallint  NULL, PB smallint  NULL, WP smallint  NULL, SB smallint  NULL, CS smallint  NULL, ZR double  NULL);
CREATE COLUMN TABLE  FieldingOF ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, stint integer  NOT NULL, Glf integer  NULL, Gcf integer  NULL, Grf integer  NULL);
CREATE COLUMN TABLE  Managers ( managerID varchar (10) NOT NULL, yearID smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, inseason smallint  NOT NULL, G smallint  NOT NULL, W smallint  NOT NULL, L smallint  NOT NULL, rank smallint  NOT NULL, plyrMgr char (1) NULL);
CREATE COLUMN TABLE  AllstarFull ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, gameNum tinyint  NOT NULL, game_id varchar (12) NOT NULL, teamID char (3) NULL, lgID char (2) NOT NULL, GP tinyint  NULL, startingPos tinyint  NULL);
CREATE COLUMN TABLE  HallOfFame ( hofID varchar (10) NOT NULL, yearID smallint  NOT NULL, votedBy varchar (64) NOT NULL, ballots smallint  NULL, needed integer  NULL, votes smallint  NULL, inducted char (1) NULL, category varchar (20) NULL, needed_note varchar (200) NULL);


-- HANA DOESN'T like 2B or 3B so Two_B and Three_B are the replacements
CREATE COLUMN TABLE  BattingPost ( yearID smallint  NOT NULL, round varchar (10) NOT NULL, playerID varchar (9) NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, G smallint  NULL, AB smallint  NOT NULL, R smallint  NULL, H smallint  NULL, TWO_B smallint  NULL, Three_B smallint  NULL, HR smallint  NOT NULL, RBI smallint  NULL, SB smallint  NULL, CS smallint  NULL, BB smallint  NULL, SO smallint  NULL, IBB smallint  NULL, HBP smallint  NULL, SH smallint  NULL, SF smallint  NULL, GIDP smallint  NULL);

CREATE COLUMN TABLE  FieldingPost ( playerID varchar (9) NOT NULL, yearID smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NOT NULL, round varchar (10) NOT NULL, POS char (2) NOT NULL, G smallint  NULL, GS smallint  NULL, InnOuts integer  NULL, PO smallint  NULL, A smallint  NULL, E smallint  NULL, DP smallint  NULL, TP smallint  NULL, PB smallint  NULL, SB smallint  NULL, CS smallint  NULL);
CREATE COLUMN TABLE  CollegePlaying ( playerID varchar (9) NOT NULL, schoolID varchar (15) NOT NULL, year integer  NOT NULL);
CREATE COLUMN TABLE  Appearances ( yearID smallint  NOT NULL, teamID char (3) NOT NULL, lgID char (2) NULL, playerID char (9) NOT NULL, G_all tinyint  NULL, GS tinyint  NULL, G_batting tinyint  NULL, G_defense tinyint  NULL, G_p tinyint  NULL, G_c tinyint  NULL, G_1b tinyint  NULL, G_2b tinyint  NULL, G_3b tinyint  NULL, G_ss tinyint  NULL, G_lf tinyint  NULL, G_cf tinyint  NULL, G_rf tinyint  NULL, G_of tinyint  NULL, G_dh tinyint  NULL, G_ph tinyint  NULL, G_pr tinyint  NULL);
CREATE COLUMN TABLE  People ( playerID varchar (9) NULL, birthYear integer  NULL, birthMonth integer  NULL, birthDay integer  NULL, birthCountry char (30) NULL, birthState char (30) NULL, birthCity char (30) NULL, deathYear integer  NULL, deathMonth integer  NULL, deathDay integer  NULL, deathCountry char (30) NULL, deathState char (30) NULL, deathCity char (30) NULL, nameFirst char (45) NULL, nameLast char (45) NULL, nameGiven char (45) NULL, weight integer  NULL, height integer  NULL, bats char (1) NULL, throws char (1) NULL, debut date  NULL, finalGame date  NULL, retroID varchar (9) NULL, bbrefID varchar (9) NULL);
CREATE COLUMN TABLE  FieldingOFsplit ( playerID char (9) NOT NULL, yearID smallint  NOT NULL, stint smallint  NOT NULL, teamID char (3) NULL, lgID char (2) NULL, POS char (2) NOT NULL, G smallint  NULL, GS smallint  NULL, InnOuts smallint  NULL, PO smallint  NULL, A smallint  NULL, E smallint  NULL, DP smallint  NULL, PB smallint  NULL, WP smallint  NULL, SB smallint  NULL, CS smallint  NULL, ZR double  NULL);
CREATE COLUMN TABLE  Parks ( ID integer  NOT NULL, parkalias varchar (100) NULL, parkkey varchar (50) NULL, parkname varchar (255) NULL, city varchar (30) NULL, state varchar (30) NULL, country varchar (30) NULL);
CREATE COLUMN TABLE  HomeGames ( yearkey smallint  NULL, leaguekey char (2) NULL, teamkey char (3) NULL, parkkey varchar (30) NULL, spanfirst date  NULL, spanlast date  NULL, games smallint  NULL, openings smallint  NULL, attendance integer  NULL);